apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-deployment
  template:
    metadata:
      labels:
        app: user-service-deployment
    spec:
      containers:
        - name: user-service-deployment
          image: asamatdev/sh-user-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: sh-secrets
            - configMapRef:
                name: sh-config-maps
          resources:
            limits:
              memory: "256M"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service-deployment
  ports:
    - port: 8080
      targetPort: 8080