apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-user-service-deployment
  labels:
    app: dev-user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-user-service-deployment
  template:
    metadata:
      labels:
        app: dev-user-service-deployment
    spec:
      containers:
        - name: dev-user-service-deployment
          image: asamatdev/sh-user-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: dev-sh-secrets
            - configMapRef:
                name: dev-sh-config-maps
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 256Gi
              cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
  name: dev-user-service
spec:
  selector:
    app: dev-user-service-deployment
  ports:
    - port: 8080
      targetPort: 8080