apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-role
  labels:
    app: fluent-bit-role
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups: [ "" ]
    resources:
      - namespaces
      - pods
      - pods/logs
    verbs: [ "get", "list", "watch" ]